# Generated by Django 2.2.9 on 2021-04-01 08:09

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnotification',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='emailnotification',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='usernotification',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='extra_context',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
    ]
