# Generated by Django 2.2.9 on 2021-04-21 14:22

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cc',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
