# Generated by Django 2.2.9 on 2021-05-24 13:18

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnotification',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='emailnotification',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='usernotification',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='cc',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='extra_context',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
    ]
